### ISSUE TITLE
为什么 git submodule update --init 的时候报错? 

### ISSUE THREAD

**Issue by 453548460Anders** [loomnetwork/cocos-sdk#1]
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:loomnetwork/loom-js.git' into submodule path '/Users/mac/Desktop/demo/cocos-sdk/deps/loom-js' failed
Failed to clone 'deps/loom-js' a second time, aborting

**Comment by ghost** [comment]
Thanks for report, fixed.
